/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-01-28 08:22:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class guest_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <html>\r\n");
      out.write(" <head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("   <title>방명록 내용 보기</title>\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"/stylesheet.css\">\r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("     td.title { padding:4px; background-color:#e3e9ff }\r\n");
      out.write("     td.content { padding:10px; line-height:1.6em; text-align:justify; }\r\n");
      out.write("     a.list { text-decoration:none;color:black;font-size:10pt; }\r\n");
      out.write("   </style>\r\n");
      out.write("<script>\r\n");
      out.write("	function guest_del(){\r\n");
      out.write("		var flag = confirm(\"삭제할가요?\");\r\n");
      out.write("		if(flag==true){\r\n");
      out.write("			location.href=\"guest_delete.do?idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	function guest_delete(){\r\n");
      out.write("		var url=\"guest_delete.do?idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		window.open(url,\"guest_delete\",\"width=300, height=200\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</script>   \r\n");
      out.write(" </head>\r\n");
      out.write(" <body topmargin=\"0\" leftmargin=\"0\">\r\n");
      out.write("   <table border=\"0\" width=\"800\">\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td width=\"20%\"  height=\"500\" bgcolor=\"#ecf1ef\" valign=\"top\">\r\n");
      out.write("\r\n");
      out.write("		 <!--  다음에 추가할 부분 -->\r\n");
      out.write("\r\n");
      out.write("	   </td>\r\n");
      out.write("       <td width=\"80%\" valign=\"top\">&nbsp;<br>\r\n");
      out.write("         <table border=\"0\" width=\"90%\" align=\"center\">\r\n");
      out.write("           <tr>\r\n");
      out.write("             <td colspan=\"2\"><img src=\"./img/bullet-01.gif\"> \r\n");
      out.write("              <font color=\"blue\" size=\"3\">방 명 록</font><font size=\"2\"> - 글읽기</font></td>\r\n");
      out.write("           </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("       <p>\r\n");
      out.write("       <table border=\"0\" width=\"90%\" align=\"center\" cellspacing=\"0\"  style=\"border-width:1px;border-color:#0066cc;border-style:outset;\">\r\n");
      out.write("         <tr bgcolor=\"e3e9ff\">\r\n");
      out.write("           <td class=\"title\">\r\n");
      out.write("             <img src=\"./img/bullet-04.gif\"> <font size=\"2\" face=\"돋움\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font>\r\n");
      out.write("           </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("           <td class=\"content\">\r\n");
      out.write("             <p align=\"right\"><font size=\"2\" face=\"돋움\">\r\n");
      out.write("              ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  / <font size=\"2\" face=\"돋움\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.readcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("번 읽음</font>\r\n");
      out.write("             <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<p>\r\n");
      out.write("           </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("       </table>\r\n");
      out.write("\r\n");
      out.write("      <!--**** 여기서부터 게시물 내용 아래쪽의 버튼들이 나옵니다. 답변, 수정, 삭제, 목록보기 ****-->\r\n");
      out.write("      <p align=\"center\">\r\n");
      out.write("      <font size=\"2\">\r\n");
      out.write("       <!-- 목록보기 -->\r\n");
      out.write("       <a class=\"list\" href=\"guest_modify.do?idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">[수정]</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       <a class=\"list\" href=\"javascript:guest_del()\">[삭제]</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       <a class=\"list\" href=\"guest_write.do?page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">[등록]</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       <a class=\"list\" href=\"javascript:history.back()\">[뒤로]</a>&nbsp;&nbsp;&nbsp;&nbsp;       \r\n");
      out.write("      </font>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  </body>\r\n");
      out.write("  </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
