/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-02-08 05:36:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원정보수정</title>\r\n");
      out.write("<STYLE TYPE=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body { font-family: 돋움, Verdana; font-size: 9pt}\r\n");
      out.write("td   { font-family: 돋움, Verdana; font-size: 9pt; text-decoration: none; color: #000000; BACKGROUND-POSITION: left top; BACKGROUND-REPEAT: no-repeat;}\r\n");
      out.write("-->\r\n");
      out.write(".formbox {\r\n");
      out.write("	BACKGROUND-COLOR: #F0F0F0; FONT-FAMILY: \"Verdana\", \"Arial\", \"Helvetica\", \"돋움\"; FONT-SIZE:9pt\r\n");
      out.write("} \r\n");
      out.write("--->\r\n");
      out.write("</STYLE>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$(\"input[name='userid']\").on(\"change\", function(){\r\n");
      out.write("			var useridExp = /^([a-zA-Z]{1})([a-zA-Z0-9]{5,10})$/;\r\n");
      out.write("			var userid = $('#userid').val();\r\n");
      out.write("			if(!useridExp.test(userid)){\r\n");
      out.write("				userID_c.innerHTML='아이디 형식이 맞지 않습니다.';\r\n");
      out.write("				$('#userid').focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:'user_idcheck.do',\r\n");
      out.write("				type:'post',\r\n");
      out.write("				data:{'userid':userid},\r\n");
      out.write("				success:function(result){\r\n");
      out.write("					if(result==0){\r\n");
      out.write("						userID_c.innerHTML='사용가능한 아이디입니다.';\r\n");
      out.write("						$('#passwd').focus();\r\n");
      out.write("					}else{\r\n");
      out.write("						userID_c.innerHTML='중복된  아이디 입니다.';\r\n");
      out.write("						$('#userid').val('');\r\n");
      out.write("						$('#userid').focus();\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error:function(error){\r\n");
      out.write("					alert(\"error :\" + error);\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		});//id 체크끝\r\n");
      out.write("		\r\n");
      out.write("		//비번 검사\r\n");
      out.write("		$(\"input[name='repasswd']\").on(\"change\",function(){\r\n");
      out.write("			var passwd = $('#passwd').val();\r\n");
      out.write("			var repasswd = $('#repasswd').val();\r\n");
      out.write("			if(passwd!=repasswd){\r\n");
      out.write("				repasswd_c.innerHTML=\"비밀번호를 다시입력하세요\";\r\n");
      out.write("				$('#repasswd').val()='';\r\n");
      out.write("				$('#repasswd').focus();\r\n");
      out.write("			}else if(passwd==repasswd){\r\n");
      out.write("				repasswd_c.innerHTML=\"비밀번호가 확인되었습니다.\";\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function send(){\r\n");
      out.write("		if(user.name.value==\"\"){\r\n");
      out.write("			alert(\"이름을 입력하세요\");\r\n");
      out.write("			user.name.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(user.tel.value==\"\"){\r\n");
      out.write("			alert(\"전화번호을 입력하세요\");\r\n");
      out.write("			user.tel.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}else if(!tel_check(user.tel.value)){\r\n");
      out.write("			alert(\"전화번호형식오류입니다.\");\r\n");
      out.write("			user.tel.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	    // 이메일 유효성 검사\r\n");
      out.write("		if(!user.email1.value){ \r\n");
      out.write("			alert(\"이메일을 입력하세요\");\r\n");
      out.write("			user.email1.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}else if(!user.email2.value && user.email3.value==\"0\"){\r\n");
      out.write("			alert(\"이메일을 입력 또는 선택하세요\");\r\n");
      out.write("			user.email2.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}else{\r\n");
      out.write("			if(user.email3.value!=0){// 선택입력\r\n");
      out.write("				user.email2.value=user.email3.value;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		user.action=\"user_insert.do\";\r\n");
      out.write("		user.submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//전화번호 유효성 검사\r\n");
      out.write("	function tel_check(str){\r\n");
      out.write("		/*\r\n");
      out.write("		   전화번호 유효성 체크\r\n");
      out.write("		   010-xxxx-xxxx 또는  010xxxxxxxx\r\n");
      out.write("		  성공이면 true 실패이면 false\r\n");
      out.write("		*/\r\n");
      out.write("		str=str.split('-').join('');\r\n");
      out.write("		var phone=/^(010[0-9]{8})$/;\r\n");
      out.write("		return phone.test(str);	\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" LEFTMARGIN=0  TOPMARGIN=0 >\r\n");
      out.write(" \r\n");
      out.write(" <!-- 탑 메뉴 영역 삽입-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" width=\"800\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <td width=\"20%\"  bgcolor=\"#ecf1ef\" valign=\"top\" style=\"padding-left:0;\">\r\n");
      out.write("	\r\n");
      out.write("	<!--로그인 영역 삽입-->\r\n");
      out.write("\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=\"80%\" valign=\"top\">&nbsp;<img src=\"./img/title1.gif\" ><br>    \r\n");
      out.write("	<form name=user method=post>\r\n");
      out.write("	<table border=0 cellpadding=0 cellspacing=0 border=0 width=730 valign=top>\r\n");
      out.write("		<tr><td align=center><br>                            \r\n");
      out.write("			<table cellpadding=0 cellspacing=0 border=0 width=650 align=center>       \r\n");
      out.write("				<tr>\r\n");
      out.write("					<td bgcolor=\"#7AAAD5\">            \r\n");
      out.write("						<table cellpadding=0 cellspacing=0 border=0 width=100%>\r\n");
      out.write("							<tr bgcolor=#7AAAD5>\r\n");
      out.write("								<td align=left BORDER=\"0\" HSPACE=\"0\" VSPACE=\"0\"><img src=\"./img/u_b02.gif\"></td>\r\n");
      out.write("								<td align=center bgcolor=\"#7AAAD5\"><FONT COLOR=\"#FFFFFF\"><b>사용자 수정&nbsp;</b><font color=black>(</font><font color=red>&nbsp;*&nbsp;</font><font color=black>표시항목은 반드시 입력하십시요.)</font></FONT></td>\r\n");
      out.write("								<td align=right BORDER=\"0\" HSPACE=\"0\" VSPACE=\"0\"><img src=\"./img/u_b03.gif\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<table cellpadding=3 cellspacing=1 border=0 width=100%>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td width=110 bgcolor=#EFF4F8>&nbsp;회원 성명<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<input type=text name=name size=16 maxlength=20 value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">성명은 빈칸없이 입력하세요.\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;회원 ID<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<table cellspacing=0 cellpadding=0>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td align=absmiddle>\r\n");
      out.write("												<input type=text name=\"userid\" id=\"userid\" size=12 maxlength=16 value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:120\">\r\n");
      out.write("											</td>\r\n");
      out.write("											<td id=\"userID_c\"> [5~16자 이내의 영문이나 숫자만 가능합니다.]\r\n");
      out.write("                  							</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</table>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;비밀번호<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("								<input type=password name=passwd id=\"passwd\" size=8 maxlength=12 style=\"width:80\">\r\n");
      out.write("									6~12자 이내의 영문이나 숫자만 가능합니다.\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;비밀번호확인<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE><input type=password name=repasswd id=\"repasswd\" size=8 maxlength=12 value=\"\" style=\"width:80\"><font id=\"repasswd_c\" color=\"red\"> 비밀번호 확인을 위해서 비밀번호를 한번 더 입력해주세요.</font> </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;전화번호<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<input type=text name=tel size=13 maxlength=13 value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;E-mail\r\n");
      out.write("                					<font color=red>&nbsp;</font>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td bgcolor=WHITE valign=middle>\r\n");
      out.write("									<input type=\"text\" name=\"email\" maxlength=\"15\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									@ <input type=\"text\" name=\"email2\" maxlength=\"15\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									<select name=\"email3\">\r\n");
      out.write("		      							<option value=\"0\">직접입력</option>\r\n");
      out.write("		      							<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("		      							<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("		      							<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("		      							<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("		  							   </select>\r\n");
      out.write("									 <input type=\"button\"  value=\"인증하기\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<table cellpadding=0 cellspacing=0 border=0 width=100%>\r\n");
      out.write("							<tr bgcolor=#7AAAD5>\r\n");
      out.write("								<td valign=bottom>\r\n");
      out.write("									<img src=\"./img/u_b04.gif\" align=left hspace=0 vspace=0 border=0>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td align=center></td>\r\n");
      out.write("								<td valign=bottom>\r\n");
      out.write("									<img src=\"./img/u_b05.gif\" align=right hspace=0 vspace=0 border=0>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr bgcolor=#ffffff>\r\n");
      out.write("								<td colspan=3 align=center>\r\n");
      out.write("									<img src=\"./img/u_bt06.gif\" vspace=3 border=0 name=img3 onClick=\"send()\">\r\n");
      out.write("									<img src=\"./img/u_bt05.gif\" border=0 hspace=10 vspace=3 name=img4>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table> \r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write(" <!-- copyright 영역 삽입-->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
