/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-02-07 08:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>로그온</TITLE>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<STYLE TYPE=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body { font-family: 돋움, Verdana; font-size: 9pt}\r\n");
      out.write("td   { font-family: 돋움, Verdana; font-size: 9pt; text-decoration: none; color: #000000; \r\n");
      out.write("      BACKGROUND-POSITION: left top; BACKGROUND-REPEAT: no-repeat;}\r\n");
      out.write("//-->\r\n");
      out.write("</STYLE>\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("	function send(){\r\n");
      out.write("		if(user.userid.value==\"\"){\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			user.userid.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(user.passwd.value==\"\"){\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			user.passwd.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		user.action=\"/User/user_login.do\";\r\n");
      out.write("		user.submit();\r\n");
      out.write("	}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" text=\"#000000\" leftmargin=0 \r\n");
      out.write("  topmargin=0 onLoad='document.fname.userid.focus();'>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" width=\"800\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <td width=\"20%\"  bgcolor=\"#ecf1ef\" valign=\"top\" style=\"padding-left:0;\">\r\n");
      out.write("\r\n");
      out.write("	<!--로그인 영역 삽입--> \r\n");
      out.write("\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=\"80%\" valign=\"top\">&nbsp;<img src=\"./img/title1.gif\" ><br>    \r\n");
      out.write("<TABLE width=\"683\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" height=\"265\">\r\n");
      out.write("<TR>\r\n");
      out.write("  <TD width=100>&nbsp;</td>\r\n");
      out.write("  <TD>\r\n");
      out.write("    <table width=\"583\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" height=\"265\">\r\n");
      out.write("	  <form name=user method=post >\r\n");
      out.write("	    <tr>\r\n");
      out.write("		  <td height=\"298\"> \r\n");
      out.write("		    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("			  <tr> \r\n");
      out.write("			    <td width=\"9\"><img src=\"./img/h_b02.gif\" width=\"9\" height=\"21\"></td>\r\n");
      out.write("				<td bgcolor=\"7aaad5\"> \r\n");
      out.write("				 <div align=\"center\"><font color=\"#FFFFFF\"><b>Member Login</b></font></div>\r\n");
      out.write("				 </td>\r\n");
      out.write("				 <td width=\"9\"><img src=\"./img/f_b03.gif\" width=\"9\" height=\"21\"></td>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			 </table>\r\n");
      out.write("			 <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"550\">\r\n");
      out.write("			   <tr> \r\n");
      out.write("			     <td bgcolor=\"#7aaad5\"> \r\n");
      out.write("				   <table border=\"0\" cellpadding=\"3\" cellspacing=\"1\" width=\"99%\" height=\"321\">\r\n");
      out.write("				     <tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("					   <td align=CENTER bgcolor=\"#eff4f8\" height=\"92\"> \r\n");
      out.write("					     <table width=\"330\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("							<tr valign=bottom> \r\n");
      out.write("							  <td width=\"21\"><img src=\"./img/h_bl02.gif\" width=\"18\" height=\"16\"></td>\r\n");
      out.write("							  <td width=\"55\" nowrap>아 이 디</td>\r\n");
      out.write("							  <td width=\"175\">: \r\n");
      out.write("								<input type=text name=\"userid\" size=16 maxlength=16 STYLE=\"WIDTH:155\">\r\n");
      out.write("							  </td>\r\n");
      out.write("							  <td width=\"79\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr valign=bottom> \r\n");
      out.write("							  <td><img src=\"./img/h_bl02.gif\" width=\"18\" height=\"16\"></td>\r\n");
      out.write("							  <td nowrap>비밀번호</td>\r\n");
      out.write("							  <td>: \r\n");
      out.write("								<input type=password name=\"passwd\" size=14 maxlength=12 STYLE=\"WIDTH:155\">\r\n");
      out.write("							  </td>\r\n");
      out.write("							  <td><input type=image src=\"./img/login.gif\" border=0 align=absmiddle onClick=\"send()\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						  </table>\r\n");
      out.write("						</td>\r\n");
      out.write("					  </tr>\r\n");
      out.write("					  <tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("						<td bgcolor=\"#ffffff\" align=CENTER height=\"138\"> \r\n");
      out.write("							[아이디찾기] &nbsp;&nbsp; [비밀번호찾기]\r\n");
      out.write("						</td>\r\n");
      out.write("					  </tr>\r\n");
      out.write("\r\n");
      out.write("					  <tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("						<td bgcolor=\"#ffffff\" align=CENTER height=\"138\"> \r\n");
      out.write("						  <table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("							<tr> \r\n");
      out.write("							  <td> \r\n");
      out.write("								<table cellpadding=2 cellspacing=0 align=center border=0>\r\n");
      out.write("								  <tr> \r\n");
      out.write("									<td> \r\n");
      out.write("										<p style=\"LINE-HEIGHT:15PX;\"><font color=\"#AFAFB1\">\r\n");
      out.write("										이곳은 JSP를 배우고자 하는 분이면 누구나\r\n");
      out.write("										   <FONT COLOR=\"#006F70\">회원가입 할 수 있는 </FONT>곳입니다.<BR><BR>\r\n");
      out.write("									</td> \r\n");
      out.write("								  </tr> \r\n");
      out.write("					              <tr> \r\n");
      out.write("							        <td> \r\n");
      out.write("							          <p style=\"LINE-HEIGHT:15PX;\"><font color=\"#AFAFB1\">아이디가 \r\n");
      out.write("								      없으신 분은 \r\n");
      out.write("							          <font color=\"#ff7508\">이용자가입</font>을 하시기 바랍니다.<br>\r\n");
      out.write("							            <br>\r\n");
      out.write("							            <br>\r\n");
      out.write("							          </p>\r\n");
      out.write("							       </td>\r\n");
      out.write("							      </tr>\r\n");
      out.write("						         </table>\r\n");
      out.write("						       </td>\r\n");
      out.write("					         </tr>\r\n");
      out.write("					       </table>\r\n");
      out.write("				         </td>\r\n");
      out.write("				       </tr>\r\n");
      out.write("			         </table>\r\n");
      out.write("			  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr> \r\n");
      out.write("				  <td width=\"9\"><img src=\"./img/h_b04.gif\" width=\"12\" height=\"11\"></td>\r\n");
      out.write("				  <td bgcolor=\"7aaad5\" width=\"612\"> \r\n");
      out.write("					<div align=\"center\"></div>\r\n");
      out.write("				  </td>\r\n");
      out.write("				  <td width=\"10\"><img src=\"./img/h_b05.gif\" width=\"12\" height=\"11\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			  </table>\r\n");
      out.write("			</td>\r\n");
      out.write("  		</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
